"""Generate key statistics for the rise-teacher paper.

Runs on all available eval outputs and produces a paper_stats.json
with the main numbers and a paper_stats.md for easy reference.

Usage:
    python scripts/gen_paper_stats.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


EVAL_DIRS = {
    "Wan5B-3s": "/data/zyf/rise-teacher/outputs/eval_pilot_v0_1",
    "Wan5B-3s-ext": "/data/zyf/rise-teacher/outputs/eval_pilot_v0_1_extended",
    "Wan5B-3s-ext6": "/data/zyf/rise-teacher/outputs/eval_pilot_v0_1_extended6",
    "Wan1.3B-3s": "/data/zyf/rise-teacher/outputs/eval_pilot_v0_1_wan13b",
    "Wan5B-5s": "/data/zyf/rise-teacher/outputs/eval_pilot_v0_1_5s",
    "Wan1.3B-5s": "/data/zyf/rise-teacher/outputs/eval_pilot_v0_1_wan13b_5s",
    "Wan1.3B-v0.2-high": "/data/zyf/rise-teacher/outputs/eval_pilot_v0_2_high",
}


def load_agg(path: str) -> dict | None:
    p = Path(path) / "aggregate.json"
    if not p.exists():
        return None
    return json.loads(p.read_text())


def main() -> None:
    stats: dict = {}
    for label, path in EVAL_DIRS.items():
        agg = load_agg(path)
        if agg is None:
            print(f"  skip {label}: no aggregate.json")
            continue
        stats[label] = {
            "n": agg["n_total"],
            "mean": agg["mean_aggregate"],
            "strict_acc": agg["strict_accuracy"],
            "dims": agg["per_dim_mean"],
            "per_difficulty": agg.get("per_difficulty", {}),
            "per_task_type": agg.get("per_task_type", {}),
        }
        print(f"  {label}: n={agg['n_total']}, mean={agg['mean_aggregate']}, strict={agg['strict_accuracy']}")

    Path("docs").mkdir(exist_ok=True)
    out_json = Path("docs/paper_stats.json")
    out_json.write_text(json.dumps(stats, indent=2, ensure_ascii=False))
    print(f"\nwrote {out_json}")

    # Markdown summary
    lines = ["# rise-teacher paper statistics\n"]

    lines.append("## Headline (aggregate 1-5, strict accuracy)\n")
    lines.append("| Model | N | Mean | Strict acc |")
    lines.append("|---|---|---|---|")
    for label, s in stats.items():
        lines.append(f"| {label} | {s['n']} | {s['mean']} | {s['strict_acc']*100:.1f}% |")

    lines.append("\n## Per dimension\n")
    all_dims = sorted({d for s in stats.values() for d in s["dims"]})
    lines.append("| Dim | " + " | ".join(stats.keys()) + " |")
    lines.append("|---|" + "|".join(["---"] * len(stats)) + "|")
    for d in all_dims:
        row = [d] + [str(s["dims"].get(d, "—")) for s in stats.values()]
        lines.append("| " + " | ".join(row) + " |")

    lines.append("\n## Per difficulty (where available)\n")
    all_diff = sorted({d for s in stats.values() for d in s["per_difficulty"]})
    if all_diff:
        lines.append("| Difficulty | " + " | ".join(stats.keys()) + " |")
        lines.append("|---|" + "|".join(["---"] * len(stats)) + "|")
        for d in all_diff:
            row = [d]
            for s in stats.values():
                entry = s["per_difficulty"].get(d)
                row.append(str(entry["mean"]) if entry else "—")
            lines.append("| " + " | ".join(row) + " |")

    lines.append("\n## Per task type\n")
    all_tt = sorted({d for s in stats.values() for d in s["per_task_type"]})
    lines.append("| Task | " + " | ".join(stats.keys()) + " |")
    lines.append("|---|" + "|".join(["---"] * len(stats)) + "|")
    for d in all_tt:
        row = [d]
        for s in stats.values():
            entry = s["per_task_type"].get(d)
            row.append(str(entry["mean"]) if entry else "—")
        lines.append("| " + " | ".join(row) + " |")

    lines.append(f"\n_Generated by scripts/gen_paper_stats.py_")

    out_md = Path("docs/paper_stats.md")
    out_md.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out_md}")


if __name__ == "__main__":
    main()
